# Generated by Django 4.1.9 on 2023-05-28 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historial_Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.IntegerField(null=True)),
                ('fecha_compra', models.DateField(auto_now_add=True)),
                ('estado_despacho', models.CharField(max_length=500)),
                ('total', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'db.Historial_Compra',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('Id_producto', models.IntegerField(primary_key=True, serialize=False)),
                ('precio', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'db.Producto',
            },
        ),
        migrations.CreateModel(
            name='Solicitud_Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.IntegerField(null=True)),
                ('Producto', models.IntegerField(null=True)),
                ('Descripcion', models.TextField(null=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_servicio', models.DateField()),
            ],
            options={
                'db_table': 'db.Solicitud_Servicio',
            },
        ),
        migrations.CreateModel(
            name='items_carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.IntegerField(null=True)),
                ('cantidad', models.IntegerField(null=True)),
                ('total', models.IntegerField(null=True)),
                ('productos', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='app.producto')),
            ],
            options={
                'db_table': 'db.Items_carrito',
            },
        ),
        migrations.CreateModel(
            name='Historial_Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.IntegerField(null=True)),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(max_length=30)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('servicio', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='app.solicitud_servicio')),
            ],
            options={
                'db_table': 'db.Historial_Servicio',
            },
        ),
        migrations.CreateModel(
            name='Boleta_Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.IntegerField(null=True)),
                ('cantidad', models.IntegerField(null=True)),
                ('id_compra', models.IntegerField(null=True)),
                ('productos', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='app.producto')),
            ],
            options={
                'db_table': 'db.Boleta_Compra',
            },
        ),
    ]
